//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace vfs.clients.web {
    
    
    public partial class Close {
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new vfs.clients.web.SiteMaster Master {
            get {
                return ((vfs.clients.web.SiteMaster)(base.Master));
            }
        }
    }
}
